[patch.crates-io]
proc-maps = { path = "lib/proc-maps" }

[workspace]
members = [
    "fuzztruction_shared",
    "scheduler",
    "generator/agent",
    "lib/proc-maps",
    "lib/jail",
    "lib/compute_coverage",
]
edition = "2021"
exclude = ["lib/llvm-stackmap-rs"]